version: '3'
services:
    clasp:
        build:
            context: .
        volumes:
            - "./:/home/node/work"
#        user: 1000:1000
#        working_dir: /home/node/work
        tty: true
